# Generated by Django 6.0.7 on 2026-07-25 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date', 'start_time'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Workshop', 'Workshop'), ('Seminar', 'Seminar'), ('Hackathon', 'Hackathon'), ('Competition', 'Competition'), ('Webinar', 'Webinar')], default='Workshop', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default=datetime.date(2026, 7, 25), max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='event',
            name='available_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=True, help_text='True = Active, False = Inactive'),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
