# Generated by Django 6.0.7 on 2026-08-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_event_category_event_organizer_and_more'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('event', 'email'), name='unique_event_registration'),
        ),
    ]
